services:
    timestampable_event_listener:
        class: MuCr\AppBundle\EventListener\Timestampable\UpdateTimestampEventListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
